name: Deploy MonitorApp on Pi

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Update repository
        run: |
          cd /home/joonas-raspi/development/MonitorApp
          git fetch --all
          git reset --hard origin/main

      - name: Deploy backend
        run: |
          cd /home/joonas-raspi/development/MonitorApp/backend
          rm -rf node_modules
          npm ci --production
          npm rebuild better-sqlite3

      - name: Build frontend
        run: |
          cd /home/joonas-raspi/development/MonitorApp/frontend
          rm -rf node_modules
          npm ci
          npm install @rolldown/binding-linux-arm64-gnu@1.2.6 --no-save
          npm run build

      - name: Restart MonitorApp
        run: |
          cd /home/joonas-raspi/development/MonitorApp/backend
          pm2 restart MonitorApp || pm2 start src/index.js --name MonitorApp
